// apps/platform/src/components/ui/switch.tsx
"use client";

import * as React from "react";
import * as SwitchPrimitives from "@radix-ui/react-switch";

import { cn } from "@/lib/utils";

const Switch = React.forwardRef<
  React.ElementRef<typeof SwitchPrimitives.Root>,
  React.ComponentPropsWithoutRef<typeof SwitchPrimitives.Root>
>(({ className, ...props }, ref) => (
  <SwitchPrimitives.Root
    className={cn(
      "peer inline-flex h-6 w-11 shrink-0 cursor-pointer items-center rounded-none border-2 border-transparent transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-blue-600 data-[state=unchecked]:bg-gray-200 dark:data-[state=checked]:bg-blue-500 dark:data-[state=unchecked]:bg-gray-700",
      className,
    )}
    {...props}
    ref={ref}
    role="switch"
  >
    <SwitchPrimitives.Thumb
      className={cn(
        "pointer-events-none block h-5 w-5 rounded-none bg-white dark:bg-gray-100 shadow-lg ring-0 transition-transform data-[state=checked]:translate-x-5 data-[state=unchecked]:translate-x-0",
      )}
    />
  </SwitchPrimitives.Root>
));
Switch.displayName = SwitchPrimitives.Root.displayName;

export { Switch };

// ishanparihar-svelte-migrated/src/lib/components/ui/Switch.svelte
<script lang="ts">
  let { 
    checked = $bindable(false),
    disabled = false,
    'aria-label': ariaLabel = undefined,
    title = undefined,
    class: className = '' 
  } = $props<{ 
    checked?: boolean;
    disabled?: boolean;
    'aria-label'?: string;
    title?: string;
    class?: string;
  }>();
  
  function handleClick() {
    if (!disabled) {
      checked = !checked;
    }
  }
</script>

<button
  type="button"
  role="switch"
  aria-checked={checked}
  aria-label={ariaLabel}
  title={title}
  onclick={handleClick}
  disabled={disabled}
  class={className + " relative inline-flex h-6 w-11 flex-shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors duration-200 ease-in-out focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed " + (checked ? 'bg-blue-600' : 'bg-gray-200')}
>
  <span
    class={"pointer-events-none relative inline-block h-5 w-5 transform rounded-full bg-white shadow ring-0 transition duration-200 ease-in-out " + (checked ? 'translate-x-5' : 'translate-x-0')}
  >
    <span
      class={"absolute inset-0 flex h-full w-full items-center justify-center transition-opacity " + (checked ? 'opacity-0 duration-100 ease-out' : 'opacity-100 duration-200 ease-in')}
      aria-hidden="true"
    >
      <svg class="h-3 w-3 text-gray-400" fill="none" viewBox="0 0 12 12">
        <path d="M4 8l2-2m0 0l2-2M6 6L4 4m2 2l2 2" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
      </svg>
    </span>
    <span
      class={"absolute inset-0 flex h-full w-full items-center justify-center transition-opacity " + (checked ? 'opacity-100 duration-200 ease-in' : 'opacity-0 duration-100 ease-out')}
      aria-hidden="true"
    >
      <svg class="h-3 w-3 text-blue-600" fill="currentColor" viewBox="0 0 12 12">
        <path d="M3.707 5.293a1 1 0 00-1.414 1.414l1.414-1.414zm2.586 2.586a1 1 0 001.414-1.414l-1.414 1.414zm-1.414-1.414a1 1 0 001.414 1.414l-1.414-1.414zm-1.414 1.414a1 1 0 001.414-1.414l-1.414 1.414zm-2.586-2.586a1 1 0 001.414 1.414l-1.414-1.414zm2.586 2.586a1 1 0 00-1.414-1.414l1.414 1.414zm4.242-4.242a1 1 0 00-1.414-1.414l1.414 1.414zm-1.414 1.414a1 1 0 001.414 1.414l-1.414-1.414zm1.414-1.414a1 1 0 00-1.414 1.414l1.414-1.414zm1.414 1.414a1 1 0 001.414-1.414l-1.414 1.414zm-4.242 4.242a1 1 0 001.414 1.414l-1.414-1.414z" />
      </svg>
    </span>
  </span>
</button>
